# Uncomment the next line to define a global platform for your project
source 'https://github.com/firebase/abseil-cpp-SwiftPM.git' 
source 'https://github.com/Alamofire/Alamofire' 
source 'https://github.com/firebase/boringssl-SwiftPM.git' 
source 'https://github.com/CocoaLumberjack/CocoaLumberjack.git' 
source 'https://github.com/firebase/firebase-ios-sdk' 
source 'https://github.com/scenee/FloatingPanel' 
source 'https://github.com/google/GoogleAppMeasurement.git' 
source 'https://github.com/google/GoogleDataTransport.git' 
source 'https://github.com/google/GoogleUtilities.git' 
source 'https://github.com/firebase/grpc-SwiftPM.git' 
source 'https://github.com/google/gtm-session-fetcher.git' 
source 'https://github.com/nextcloud/ios-communication-library/' 
source 'https://github.com/firebase/leveldb.git' 
source 'https://github.com/bmoliveira/MarkdownKit' 
source 'https://github.com/firebase/nanopb.git' 
source 'https://github.com/rechsteiner/Parchment' 
source 'https://github.com/google/promises.git' 
source 'https://github.com/yannickl/QRCodeReader.swift' 
source 'https://github.com/huri000/QuickLayout' 
source 'https://github.com/realm/realm-cocoa' 
source 'https://github.com/realm/realm-core' 
source 'https://github.com/SVGKit/SVGKit.git' 
source 'https://github.com/apple/swift-log.git' 
source 'https://github.com/apple/swift-protobuf.git' 
source 'https://github.com/huri000/SwiftEntryKit' 
source 'https://github.com/malcommac/SwiftRichString' 
source 'https://github.com/SwiftyJSON/SwiftyJSON' 
source 'https://github.com/yahoojapan/SwiftyXMLParser'
platform :ios, '9.0'

target 'File Provider Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for File Provider Extension
pod 'abseil', '~> 0.20200225.3'
pod 'Alamofire', '~> 5.4.3'
pod 'BoringSSL-GRPC', '~> 0.7.1'
pod 'CocoaLumberjack', '~> 3.7.0'
pod 'Firebase', '~> 7.11.1'
pod 'FloatingPanel', '~> 1.7.6'
pod 'GoogleAppMeasurement', '~> 7.11.1'
pod 'GoogleDataTransport', '~> 8.4.0'
pod 'GoogleUtilities', '~> 7.4.0'
pod 'gRPC', '~> 1.28.4'
pod 'GTMSessionFetcher', '~> 1.5.0'
pod 'NCCommunication', '~> 0.99.2'
pod 'leveldb', '~> 1.22.2'
pod 'MarkdownKit', '~> 1.7.1'
pod 'nanopb', '~> 2.30908.0'
pod 'Parchment', '~> 3.0.1'
pod 'Promises', '~> 1.2.12'
pod 'QRCodeReader', '~> 10.1.1'
pod 'QuickLayout', '~> 3.0.1'
pod 'Realm', '~> 10.10.0'
pod 'RealmDatabase', '~> 11.0.4'
pod 'SVGKit', '~> null'
pod 'swift-log', '~> 1.4.0'
pod 'SwiftProtobuf', '~> 1.16.0'
pod 'SwiftEntryKit', '~> 1.2.7'
pod 'SwiftRichString', '~> 3.7.2'
pod 'SwiftyJSON', '~> 5.0.1'
pod 'SwiftyXMLParser', '~> 5.3.0'
end
