name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: carthage update --use-xcframeworks --platform iOS --cache-builds
           xcodebuild clean build   -project Nextcloud.xcodeproj \
                        -destination "platform=iOS"
 
