name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: carthage update --use-xcframeworks --platform iOS --cache-builds
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v                  
